<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = \Carbon\Carbon::now();
        $countries = [
            [1,'Afganistán', 'Afgana','AF'],
            [2,'Albania', 'Albanesa','AL'],
            [3,'Alemania', 'Alemana','DE'],
            [4,'Andorra', 'Andorrana','AD'],
            [5,'Angola', 'Angoleña','AO'],
            [6,'Antigua y Barbuda', 'Antiguana','AG'],
            [7,'Arabia Saudita', 'Saudí','SA'],
            [8,'Argelia', 'Argelina','DZ'],
            [9,'Argentina', 'Argentina','AR'],
            [10,'Armenia', 'Armenia','AM'],
            [11,'Aruba', 'Arubeña','AW'],
            [12,'Australia', 'Australiana','AU'],
            [13,'Austria', 'Austriaca','AT'],
            [14,'Azerbaiyán', 'Azerbaiyana','AZ'],
            [15,'Bahamas', 'Bahameña','BT'],
            [16,'Bangladés', 'Bangladesí','BD'],
            [17,'Barbados', 'Barbadense','BB'],
            [18,'Baréin', 'Bareiní','BH'],
            [19,'Bélgica', 'Belga','BE'],
            [20,'Belice', 'Beliceña','BZ'],
            [21,'Benín', 'Beninésa','BJ'],
            [22,'Bielorrusia', 'Bielorrusa','BY'],
            [23,'Birmania', 'Birmana','MM'],
            [24,'Bolivia', 'Boliviana','BO'],
            [25,'Bosnia y Herzegovina', 'Bosnia','BA'],
            [26,'Botsuana', 'Botsuana','BW'],
            [27,'Brasil', 'Brasileña','BR'],
            [28,'Brunéi', 'Bruneana','BN'],
            [29,'Bulgaria', 'Búlgara','BG'],
            [30,'Burkina Faso', 'Burkinés','BF'],
            [31,'Burundi', 'Burundésa','BI'],
            [32,'Bután', 'Butanésa','BS'],
            [33,'Cabo Verde', 'Caboverdiana','CV'],
            [34,'Camboya', 'Camboyana','KH'],
            [35,'Camerún', 'Camerunesa','CM'],
            [36,'Canadá', 'Canadiense','CA'],
            [37,'Catar', 'Catarí','QA'],
            [38,'Chad', 'Chadiana','TD'],
            [39,'Chile', 'Chilena','CL'],
            [40,'China', 'China','CN'],
            [41,'Chipre', 'Chipriota','CY'],
            [42,'Ciudad del Vaticano', 'Vaticana','VA'],
            [43,'Colombia', 'Colombiana','CO'],
            [44,'Comoras', 'Comorense','KM'],
            [45,'Corea del Norte', 'Norcoreana','KP'],
            [46,'Corea del Sur', 'Surcoreana','KR'],
            [47,'Costa de Marfil', 'Marfileña','CI'],
            [48,'Costa Rica', 'Costarricense','CR'],
            [49,'Croacia', 'Croata','HR'],
            [50,'Cuba', 'Cubana','CU'],
            [51,'Dinamarca', 'Danésa','DK'],
            [52,'Dominica', 'Dominiqués','DM'],
            [53,'Ecuador', 'Ecuatoriana','EC'],
            [54,'Egipto', 'Egipcia','EG'],
            [55,'El Salvador', 'Salvadoreña','SV'],
            [56,'Emiratos Árabes Unidos', 'Emiratí','AE'],
            [57,'Eritrea', 'Eritrea','ER'],
            [58,'Eslovaquia', 'Eslovaca','SK'],
            [59,'Eslovenia', 'Eslovena','SI'],
            [60,'España', 'Española','ES'],
            [61,'Estados Unidos', 'Estadounidense','US'],
            [62,'Estonia', 'Estonia','EE'],
            [63,'Etiopía', 'Etíope','ET'],
            [64,'Filipinas', 'Filipina','PH'],
            [65,'Finlandia', 'Finlandésa','FI'],
            [66,'Fiyi', 'Fiyiana','FJ'],
            [67,'Francia', 'Francésa','FR'],
            [68,'Gabón', 'Gabonésa','GA'],
            [69,'Gambia', 'Gambiana','GM'],
            [70,'Georgia', 'Georgiana','GE'],
            [71,'Gibraltar', 'Gibraltareña','GI'],
            [72,'Ghana', 'Ghanésa','GH'],
            [73,'Granada', 'Granadina','GD'],
            [74,'Grecia', 'Griega','GR'],
            [75,'Groenlandia', 'Groenlandésa','GL'],
            [76,'Guatemala', 'Guatemalteca','GT'],
            [77,'Guinea ecuatorial', 'Ecuatoguineana','GQ'],
            [78,'Guinea', 'Guineana','GN'],
            [79,'Guinea-Bisáu', 'Guineana','GW'],
            [80,'Guyana', 'Guyanesa','GY'],
            [81,'Haití', 'Haitiana','HT'],
            [82,'Honduras', 'Hondureña','HN'],
            [83,'Hungría', 'Húngara','HU'],
            [84,'India', 'Hindú','IN'],
            [85,'Indonesia', 'Indonesia','ID'],
            [86,'Irak', 'Iraquí','IQ'],
            [87,'Irán', 'Iraní','IR'],
            [88,'Irlanda', 'Irlandésa','IE'],
            [89,'Islandia', 'Islandésa','IS'],
            [90,'Islas Cook', 'Cookiana','CK'],
            [91,'Islas Marshall', 'Marshalésa','FK'],
            [92,'Islas Salomón', 'Salomonense','SB'],
            [93,'Israel', 'Israelí','IL'],
            [94,'Italia', 'Italiana','IT'],
            [95,'Jamaica', 'Jamaiquina','JM'],
            [96,'Japón', 'Japonésa','JP'],
            [97,'Jordania', 'Jordana','JO'],
            [98,'Kazajistán', 'Kazaja','KZ'],
            [99,'Kenia', 'Keniata','KE'],
            [100,'Kirguistán', 'Kirguisa','KG'],
            [101,'Kiribati', 'Kiribatiana','KI'],
            [102,'Kuwait', 'Kuwaití','KW'],
            [103,'Laos', 'Laosiana','LA'],
            [104,'Lesoto', 'Lesotense','LS'],
            [105,'Letonia', 'Letóna','LV'],
            [106,'Líbano', 'Libanésa','LB'],
            [107,'Liberia', 'Liberiana','LR'],
            [108,'Libia', 'Libia','LY'],
            [109,'Liechtenstein', 'Liechtensteiniana','LI'],
            [110,'Lituania', 'Lituana','LT'],
            [111,'Luxemburgo', 'Luxemburguésa','LU'],
            [112,'Madagascar', 'Malgache','MG'],
            [113,'Malasia', 'Malasia','MY'],
            [114,'Malaui', 'Malauí','MW'],
            [115,'Maldivas', 'Maldiva','MV'],
            [116,'Malí', 'Maliense','ML'],
            [117,'Malta', 'Maltésa','MT'],
            [118,'Marruecos', 'Marroquí','MA'],
            [119,'Martinica', 'Martiniqués','MQ'],
            [120,'Mauricio', 'Mauriciana','MU'],
            [121,'Mauritania', 'Mauritana','MR'],
            [122,'México', 'Mexicana','MX'],
            [123,'Micronesia', 'Micronesia','FM'],
            [124,'Moldavia', 'Moldava','MD'],
            [125,'Mónaco', 'Monegasca','MC'],
            [126,'Mongolia', 'Mongola','MN'],
            [127,'Montenegro', 'Montenegrina','ME'],
            [128,'Mozambique', 'Mozambiqueña','MZ'],
            [129,'Namibia', 'Namibia','NA'],
            [130,'Nauru', 'Nauruana','NR'],
            [131,'Nepal', 'Nepalí','NP'],
            [132,'Nicaragua', 'Nicaragüense','NI'],
            [133,'Níger', 'Nigerina','NE'],
            [134,'Nigeria', 'Nigeriana','NG'],
            [135,'Noruega', 'Noruega','NO'],
            [136,'Nueva Zelanda', 'Neozelandésa','NZ'],
            [137,'Omán', 'Omaní','OM'],
            [138,'Países Bajos', 'Neerlandésa','NL'],
            [139,'Pakistán', 'Pakistaní','PK'],
            [140,'Palaos', 'Palauana','PW'],
            [141,'Palestina', 'Palestina','PS'],
            [142,'Panamá', 'Panameña','PA'],
            [143,'Papúa Nueva Guinea', 'Papú','PG'],
            [144,'Paraguay', 'Paraguaya','PY'],
            [145,'Perú', 'Peruana','PE'],
            [146,'Polonia', 'Polaca','PL'],
            [147,'Portugal', 'Portuguésa','PT'],
            [148,'Puerto Rico', 'Puertorriqueña','PR'],
            [149,'Reino Unido', 'Británica','GB'],
            [150,'República Centroafricana', 'Centroafricana','CF'],
            [151,'República Checa', 'Checa','CZ'],
            [152,'República de Macedonia', 'Macedonia','MK'],
            [153,'República del Congo', 'Congoleña','CG'],
            [154,'República Democrática del Congo', 'Congoleña','CD'],
            [155,'República Dominicana', 'Dominicana','DO'],
            [156,'República Sudafricana', 'Sudafricana','ZA'],
            [157,'Ruanda', 'Ruandésa','RW'],
            [158,'Rumanía', 'Rumana','RO'],
            [159,'Rusia', 'Rusa','RU'],
            [160,'Samoa', 'Samoana','WS'],
            [161,'San Cristóbal y Nieves', 'Cristobaleña','KN'],
            [162,'San Marino', 'Sanmarinense','SM'],
            [163,'San Vicente y las Granadinas', 'Sanvicentina','VC'],
            [164,'Santa Lucía', 'Santalucense','LC'],
            [165,'Santo Tomé y Príncipe', 'Santotomense','ST'],
            [166,'Senegal', 'Senegalésa','SN'],
            [167,'Serbia', 'Serbia','RS'],
            [168,'Seychelles', 'Seychellense','SC'],
            [169,'Sierra Leona', 'Sierraleonésa','SL'],
            [170,'Singapur', 'Singapurense','SG'],
            [171,'Siria', 'Siria','SY'],
            [172,'Somalia', 'Somalí','SO'],
            [173,'Sri Lanka', 'Ceilanésa','LK'],
            [174,'Suazilandia', 'Suazi','SZ'],
            [175,'Sudán del Sur', 'Sursudanésa','SS'],
            [176,'Sudán', 'Sudanésa','SD'],
            [177,'Suecia', 'Sueca','SE'],
            [178,'Suiza', 'Suiza','CH'],
            [179,'Surinam', 'Surinamesa','SR'],
            [180,'Tailandia', 'Tailandésa','TH'],
            [181,'Tanzania', 'Tanzana','TZ'],
            [182,'Tayikistán', 'Tayika','TJ'],
            [183,'Timor Oriental', 'Timorense','TP'],
            [184,'Togo', 'Togolésa','TG'],
            [185,'Tonga', 'Tongana','TO'],
            [186,'Trinidad y Tobago', 'Trinitense','TT'],
            [187,'Túnez', 'Tunecina','TN'],
            [188,'Turkmenistán', 'Turcomana','TM'],
            [189,'Turquía', 'Turca','TR'],
            [190,'Tuvalu', 'Tuvaluana','TV'],
            [191,'Ucrania', 'Ucraniana','UA'],
            [192,'Uganda', 'Ugandésa','UG'],
            [193,'Uruguay', 'Uruguaya','UY'],
            [194,'Uzbekistán', 'Uzbeka','UZ'],
            [195,'Vanuatu', 'Vanuatuense','VU'],
            [196,'Venezuela', 'Venezolana','VE'],
            [197,'Vietnam', 'Vietnamita','VN'],
            [198,'Yemen', 'Yemení','YE'],
            [199,'Yibuti', 'Yibutiana','DJ'],
            [200,'Zambia', 'Zambiana','ZM'],
            [201,'Zimbabue', 'Zimbabuense','ZW'],
        ];

        $countries = array_map(function($country) use ($now) {
           return [
               'id' => $country[0],
               'name' => $country[1],
               'demonym' => $country[2],
               'cod' => $country[3],
               'updated_at' => $now,
               'created_at' => $now,
           ];
        }, $countries);

        \DB::table('countries')->insert($countries);
    }
}
